SELECT TOP (1000)
    [UserID]
      , [EmployeeID]
      , [Username]
      , [PasswordHash]
      , [Role]
      , [IsLocked]
      , [FailedLoginAttempts]
      , [LockoutEnd]
      , [LastLogin]
      , [LastPasswordChange]
      , [CreatedBy]
      , [CreatedByName]
      , [CreatedDate]
      , [ModifiedBy]
      , [ModifiedByName]
      , [ModifiedDate]
      , [IsActive]
FROM [NovaStaffDB].[dbo].[Users]