// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.SqlServer.Types;
using NovaStaff.DataLayers;

#nullable disable

namespace NovaStaff.DataLayers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510155841_FixPayrollPaidDateConstraint")]
    partial class FixPayrollPaidDateConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("EmployeeCodeSequence")
                .StartsAt(1000L);

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasComment("M? đ?nh danh ph?ng ban");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Tên ph?ng ban/b? ph?n");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ManagerEmployeeID")
                        .HasColumnType("int")
                        .HasComment("ID nhân viên đang gi? ch?c v? trư?ng ph?ng");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("OrgLevel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasComputedColumnSql("[OrgNode].GetLevel()", false);

                    b.Property<SqlHierarchyId>("OrgNode")
                        .HasColumnType("hierarchyid");

                    b.HasKey("DepartmentID");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Code")
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("ManagerEmployeeID")
                        .HasDatabaseName("IX_Departments_ManagerEmployeeID");

                    b.HasIndex("OrgNode")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_OrgNode");

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Department_Code", "Code IS NULL OR LEN(LTRIM(Code)) > 0");

                            t.HasCheckConstraint("CK_Department_Name", "LEN(LTRIM(DepartmentName)) > 0");
                        });
                });

            modelBuilder.Entity("LeaveRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHalfDayEnd")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHalfDayStart")
                        .HasColumnType("bit");

                    b.Property<byte>("LeaveType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalDays")
                        .HasColumnType("float");

                    b.HasKey("RequestID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LeaveRequests_Status");

                    b.HasIndex("EmployeeID", "FromDate")
                        .HasDatabaseName("IX_LeaveRequests_Employee_Date");

                    b.ToTable("LeaveRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequest_ApprovedBy", "ApprovedBy IS NULL OR Status <> 1");

                            t.HasCheckConstraint("CK_LeaveRequest_ApprovedDate", "ApprovedDate IS NULL OR Status <> 1");

                            t.HasCheckConstraint("CK_LeaveRequest_DateRange", "ToDate >= FromDate");

                            t.HasCheckConstraint("CK_LeaveRequest_LeaveType", "[LeaveType] IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_LeaveRequest_Status", "[Status] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.AttendanceRecord", b =>
                {
                    b.Property<long>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordID"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("WorkDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CAST(GETUTCDATE() AS DATE)");

                    b.Property<decimal?>("WorkHours")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasComputedColumnSql("CAST(  CASE    WHEN CheckIn IS NOT NULL AND CheckOut IS NOT NULL    THEN DATEDIFF(MINUTE, CheckIn, CheckOut) / 60.0    ELSE NULL  END AS decimal(5,2))", false);

                    b.HasKey("RecordID");

                    b.HasIndex("WorkDate")
                        .HasDatabaseName("IX_AttendanceRecords_WorkDate");

                    b.HasIndex("EmployeeID", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("IX_AttendanceRecords_EmployeeID_WorkDate")
                        .HasFilter("[EmployeeID] IS NOT NULL");

                    b.ToTable("AttendanceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecord_Status", "[Status] IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Attendance_ValidTime", "CheckIn IS NOT NULL OR CheckOut IS NULL");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditID"));

                    b.Property<byte>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AuditID");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_AuditLog_ChangedBy");

                    b.HasIndex("RecordID")
                        .HasDatabaseName("IX_AuditLog_RecordID");

                    b.HasIndex("TableName", "ChangedDate")
                        .HasDatabaseName("IX_AuditLog_Table_Date");

                    b.ToTable("AuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Action", "[Action] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("Lương cơ b?n hàng tháng");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("NEXT VALUE FOR EmployeeCodeSequence");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JobLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SupervisorID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("SupervisorID")
                        .HasDatabaseName("IX_Employees_SupervisorID");

                    b.HasIndex("FullName", "Status")
                        .HasDatabaseName("IX_Employees_Search_NameStatus");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Employee_BaseSalary", "[BaseSalary] >= 0");

                            t.HasCheckConstraint("CK_Employee_Gender", "[Gender] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Employee_Status", "[Status] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.PayrollDetail", b =>
                {
                    b.Property<long>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetailID"));

                    b.Property<decimal>("ActualWorkDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("BaseSalarySnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BonusAndAllowancesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeductionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetailID");

                    b.HasIndex("PeriodID")
                        .HasDatabaseName("IX_PayrollDetails_PeriodID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PayrollDetails_Status");

                    b.HasIndex("EmployeeID", "PeriodID")
                        .IsUnique()
                        .HasDatabaseName("IX_PayrollDetails_Employee_Period_Unique")
                        .HasFilter("[EmployeeID] IS NOT NULL");

                    b.ToTable("PayrollDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_PayrollDetail_NetSalary", "NetSalary >= 0");

                            t.HasCheckConstraint("CK_PayrollDetail_PaidDate", "PaidDate IS NULL OR Status = 4");

                            t.HasCheckConstraint("CK_PayrollDetail_Status", "[Status] IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_PayrollDetail_TotalIncome", "TotalIncome >= 0");

                            t.HasCheckConstraint("CK_PayrollDetail_WorkDays", "ActualWorkDays >= 0");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.PayrollPeriod", b =>
                {
                    b.Property<int>("PeriodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodID"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("PeriodID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PayrollPeriods_Status");

                    b.HasIndex("Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_PayrollPeriods_Month_Year");

                    b.ToTable("PayrollPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_PayrollPeriod_DateRange", "EndDate >= StartDate");

                            t.HasCheckConstraint("CK_PayrollPeriod_Month", "Month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_PayrollPeriod_Status", "[Status] IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.WorkTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaskID");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_WorkTasks_DueDate")
                        .HasFilter("DueDate IS NOT NULL");

                    b.HasIndex("EmployeeID", "Status")
                        .HasDatabaseName("IX_WorkTasks_Employee_Status");

                    b.ToTable("WorkTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkTask_Priority", "[Priority] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_WorkTask_Status", "[Status] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPasswordChange")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("EmployeeID")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EmployeeID")
                        .HasFilter("[EmployeeID] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("IsLocked", "LockoutEnd")
                        .HasDatabaseName("IX_Users_LockStatus");

                    b.HasIndex("IsLocked", "Role")
                        .HasDatabaseName("IX_Users_Status_Role");

                    b.HasIndex("IsLocked", "LockoutEnd", "FailedLoginAttempts")
                        .HasDatabaseName("IX_Users_Lock_Optimize");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_FailedLogins", "[FailedLoginAttempts] >= 0");

                            t.HasCheckConstraint("CK_User_LockoutEnd", "[LockoutEnd] IS NULL OR [LockoutEnd] > '2000-01-01'");

                            t.HasCheckConstraint("CK_User_Role", "[Role] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_User_Username", "LEN(LTRIM(RTRIM(Username))) > 0");
                        });
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaveRequest", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.Employee", b =>
                {
                    b.HasOne("Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovaStaff.Models.Entities.Employee", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.PayrollDetail", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovaStaff.Models.Entities.PayrollPeriod", "Period")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.WorkTask", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("User", "EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("LeaveRequests");

                    b.Navigation("PayrollDetails");

                    b.Navigation("Subordinates");

                    b.Navigation("User");

                    b.Navigation("WorkTasks");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.PayrollPeriod", b =>
                {
                    b.Navigation("PayrollDetails");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
