// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaStaff.DataLayers;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaStaff.DataLayers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("EmployeeCodeSequence")
                .StartsAt(1000L);

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasComment("Mã định danh phòng ban");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Tên phòng ban/bộ phận");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("ManagerEmployeeID")
                        .HasColumnType("int")
                        .HasComment("ID nhân viên đang giữ chức vụ trưởng phòng");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("OrgLevel")
                        .IsRequired()
                        .HasColumnType("smallint")
                        .HasComment("Cấp bậc phòng ban trong cây");

                    b.Property<string>("OrgPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Đường dẫn phân cấp phòng ban (Materialized Path)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Code");

                    b.HasIndex("ManagerEmployeeID")
                        .HasDatabaseName("IX_Departments_ManagerEmployeeID");

                    b.HasIndex("OrgPath")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_OrgPath");

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Department_Code", "\"Code\" IS NULL OR LENGTH(TRIM(\"Code\")) > 0");

                            t.HasCheckConstraint("CK_Department_Name", "LENGTH(TRIM(\"DepartmentName\")) > 0");
                        });
                });

            modelBuilder.Entity("LeaveRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestID"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsHalfDayEnd")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHalfDayStart")
                        .HasColumnType("boolean");

                    b.Property<byte>("LeaveType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<double>("TotalDays")
                        .HasColumnType("double precision");

                    b.HasKey("RequestID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LeaveRequests_Status");

                    b.HasIndex("EmployeeID", "FromDate")
                        .HasDatabaseName("IX_LeaveRequests_Employee_Date");

                    b.ToTable("LeaveRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequest_ApprovedBy", "\"ApprovedBy\" IS NULL OR \"Status\" <> 1");

                            t.HasCheckConstraint("CK_LeaveRequest_ApprovedDate", "\"ApprovedDate\" IS NULL OR \"Status\" <> 1");

                            t.HasCheckConstraint("CK_LeaveRequest_DateRange", "\"ToDate\" >= \"FromDate\"");

                            t.HasCheckConstraint("CK_LeaveRequest_LeaveType", "\"LeaveType\" IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_LeaveRequest_Status", "\"Status\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.AttendanceRecord", b =>
                {
                    b.Property<long>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordID"));

                    b.Property<DateTimeOffset?>("CheckIn")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("CheckOut")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateOnly>("WorkDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<decimal?>("WorkHours")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasComputedColumnSql("CASE WHEN \"CheckIn\" IS NOT NULL AND \"CheckOut\" IS NOT NULL THEN (EXTRACT(EPOCH FROM (\"CheckOut\" - \"CheckIn\")) / 3600.0)::numeric(5,2) ELSE NULL END", true);

                    b.HasKey("RecordID");

                    b.HasIndex("WorkDate")
                        .HasDatabaseName("IX_AttendanceRecords_WorkDate");

                    b.HasIndex("EmployeeID", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("IX_AttendanceRecords_EmployeeID_WorkDate");

                    b.ToTable("AttendanceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_AttendanceRecord_Status", "\"Status\" IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Attendance_ValidTime", "\"CheckIn\" IS NOT NULL OR \"CheckOut\" IS NULL");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditID"));

                    b.Property<byte>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("text");

                    b.Property<string>("OldData")
                        .HasColumnType("text");

                    b.Property<string>("RecordID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("AuditID");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_AuditLog_ChangedBy");

                    b.HasIndex("RecordID")
                        .HasDatabaseName("IX_AuditLog_RecordID");

                    b.HasIndex("TableName", "ChangedDate")
                        .HasDatabaseName("IX_AuditLog_Table_Date");

                    b.ToTable("AuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Action", "\"Action\" IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatChannel", b =>
                {
                    b.Property<int>("ChatChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatChannelID"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ChatChannelID");

                    b.ToTable("ChatChannels", (string)null);
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatMember", b =>
                {
                    b.Property<int>("ChatMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatMemberID"));

                    b.Property<int>("ChatChannelID")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ChatMemberID");

                    b.HasIndex("UserID");

                    b.HasIndex("ChatChannelID", "UserID")
                        .IsUnique();

                    b.ToTable("ChatMembers", (string)null);
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatMessageID"));

                    b.Property<int>("ChatChannelID")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReplyToMessageID")
                        .HasColumnType("integer");

                    b.Property<int>("SenderUserID")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ChatMessageID");

                    b.HasIndex("ReplyToMessageID");

                    b.HasIndex("SenderUserID");

                    b.HasIndex("ChatChannelID", "CreatedDate");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasComment("Lương cơ bản hàng tháng");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractType")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("nextval('\"EmployeeCodeSequence\"')");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<int?>("JobLevel")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("SupervisorID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("SupervisorID")
                        .HasDatabaseName("IX_Employees_SupervisorID");

                    b.HasIndex("FullName", "Status")
                        .HasDatabaseName("IX_Employees_Search_NameStatus");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Employee_BaseSalary", "\"BaseSalary\" >= 0");

                            t.HasCheckConstraint("CK_Employee_Gender", "\"Gender\" IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Employee_Status", "\"Status\" IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.MessageAttachment", b =>
                {
                    b.Property<int>("MessageAttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageAttachmentID"));

                    b.Property<int>("ChatMessageID")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageAttachmentID");

                    b.HasIndex("ChatMessageID");

                    b.ToTable("MessageAttachments", (string)null);
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.MessageReaction", b =>
                {
                    b.Property<int>("MessageReactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageReactionID"));

                    b.Property<int>("ChatMessageID")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("MessageReactionID");

                    b.HasIndex("UserID");

                    b.HasIndex("ChatMessageID", "UserID", "Emoji")
                        .IsUnique();

                    b.ToTable("MessageReactions", (string)null);
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.PayrollDetail", b =>
                {
                    b.Property<long>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DetailID"));

                    b.Property<decimal>("ActualWorkDays")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal>("BaseSalarySnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BonusAndAllowancesJson")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeductionsJson")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("DetailID");

                    b.HasIndex("PeriodID")
                        .HasDatabaseName("IX_PayrollDetails_PeriodID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PayrollDetails_Status");

                    b.HasIndex("EmployeeID", "PeriodID")
                        .IsUnique()
                        .HasDatabaseName("IX_PayrollDetails_Employee_Period_Unique");

                    b.ToTable("PayrollDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_PayrollDetail_NetSalary", "\"NetSalary\" >= 0");

                            t.HasCheckConstraint("CK_PayrollDetail_PaidDate", "\"PaidDate\" IS NULL OR \"Status\" = 4");

                            t.HasCheckConstraint("CK_PayrollDetail_Status", "\"Status\" IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_PayrollDetail_TotalIncome", "\"TotalIncome\" >= 0");

                            t.HasCheckConstraint("CK_PayrollDetail_WorkDays", "\"ActualWorkDays\" >= 0");
                        });
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.WorkTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskID"));

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)2);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TaskID");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_WorkTasks_DueDate")
                        .HasFilter("\"DueDate\" IS NOT NULL");

                    b.HasIndex("EmployeeID", "Status")
                        .HasDatabaseName("IX_WorkTasks_Employee_Status");

                    b.ToTable("WorkTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkTask_Priority", "\"Priority\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_WorkTask_Status", "\"Status\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("PayrollPeriod", b =>
                {
                    b.Property<int>("PeriodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodID"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("PeriodID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PayrollPeriods_Status");

                    b.HasIndex("Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_PayrollPeriods_Month_Year");

                    b.ToTable("PayrollPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_PayrollPeriod_DateRange", "\"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_PayrollPeriod_Month", "\"Month\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_PayrollPeriod_Status", "\"Status\" IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPasswordChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)3);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("EmployeeID")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EmployeeID")
                        .HasFilter("\"EmployeeID\" IS NOT NULL");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Users_IsDeleted");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("IsLocked", "LockoutEnd")
                        .HasDatabaseName("IX_Users_LockStatus");

                    b.HasIndex("IsLocked", "Role")
                        .HasDatabaseName("IX_Users_Status_Role");

                    b.HasIndex("IsLocked", "LockoutEnd", "FailedLoginAttempts")
                        .HasDatabaseName("IX_Users_Lock_Optimize");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_FailedLogins", "\"FailedLoginAttempts\" >= 0");

                            t.HasCheckConstraint("CK_User_LockoutEnd", "\"LockoutEnd\" IS NULL OR \"LockoutEnd\" > '2000-01-01'");

                            t.HasCheckConstraint("CK_User_Role", "\"Role\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_User_Username", "LENGTH(TRIM(\"Username\")) > 0");
                        });
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaveRequest", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatMember", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.ChatChannel", "Channel")
                        .WithMany("Members")
                        .HasForeignKey("ChatChannelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.ChatChannel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChatChannelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaStaff.Models.Entities.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.Employee", b =>
                {
                    b.HasOne("Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovaStaff.Models.Entities.Employee", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.MessageAttachment", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.ChatMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("ChatMessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.MessageReaction", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.ChatMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("ChatMessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.PayrollDetail", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PayrollPeriod", "Period")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.WorkTask", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("NovaStaff.Models.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("User", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatChannel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.ChatMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("NovaStaff.Models.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("LeaveRequests");

                    b.Navigation("PayrollDetails");

                    b.Navigation("Subordinates");

                    b.Navigation("User");

                    b.Navigation("WorkTasks");
                });

            modelBuilder.Entity("PayrollPeriod", b =>
                {
                    b.Navigation("PayrollDetails");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
